### PR TITLE
Fix port number is missing sometimes

### LINKED ISSUE #141: Auto discovery Docker example does not work out of the box
### The problem

Getting an error about ports not being present / valid despite specifying this in Docker compose using the example given.

### What addon are you reporting the bug for?

rtl_433_mqtt_autodiscover

### What is the addon version?

Latest

### What type of MQTT Broker are you using?

Home Assistant Mosquitto MQTT Broker

### Addon log messages

```txt
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Using an external mqtt broker.
curl: (6) Could not resolve host: supervisor
[01:29:30] ERROR: Something went wrong contacting the API
Starting rtl_433_mqtt_hass.py...
usage: rtl_433_mqtt_hass.py [-h] [-d] [-q] [-u USER] [-P PASSWORD] [-H HOST]
                            [-p PORT] [-r] [-f] [-R RTL_TOPIC]
                            [-D DISCOVERY_PREFIX] [-i DISCOVERY_INTERVAL]
rtl_433_mqtt_hass.py: error: argument -p/--port: invalid int value: 'null'
[cmd] /run.sh exited 2
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

### Additional information

```
version: '3'
services:
  rtl_433_autodiscovery:
    container_name: rtl_433_autodiscovery
    image: ghcr.io/pbkhrv/rtl_433-hass-addons-rtl_433_mqtt_autodiscovery-amd64
    environment:
      - MQTT_HOST=mqtt.example.com
      - MQTT_USERNAME=username
      - MQTT_PASSWORD=password
      # - MQTT_PORT=1883
```

or

```
version: '3'
services:
  rtl_433_autodiscovery:
    container_name: rtl_433_autodiscovery
    image: ghcr.io/pbkhrv/rtl_433-hass-addons-rtl_433_mqtt_autodiscovery-amd64
    environment:
      - MQTT_HOST=mqtt.example.com
      - MQTT_USERNAME=username
      - MQTT_PASSWORD=password
      - MQTT_PORT=1883
```

### PR DESCRIPTION
**Pull request by codyc1515**
Happens with default Docker config. Fixes #141.

## Testing Steps

1. First...
2. Then...
3. You should see... (screenshots or console text are helpful)

### CODE REVIEW

File: rtl_433_mqtt_autodiscovery/run.sh [hunk 1]
```diff
@@ -51,5 +51,9 @@ else
   fi
 fi
 
+if [ ! -z ${MQTT_PORT+x} ]; then
+  MQTT_PORT="1883"
```
Comment (deviantintegral) [inline rtl_433_mqtt_autodiscovery/run.sh:55]: Makes sense. When running in HAOS, the default is set at https://github.com/pbkhrv/rtl_433-hass-addons/blob/main/rtl_433_mqtt_autodiscovery/config.json#L14.

Let's remind ourselves of this?

```suggestion
# Set a default port for when the container is being run directly.
if [ ! -z ${MQTT_PORT+x} ]; then
  MQTT_PORT="1883"
```

**Review by deviantintegral — APPROVED** [review]
Nice fix! Thank you.

**Comment by codyc1515** [comment]
Good idea. Thanks.
